<?php $pages = $this->getMenuItems(); ?>
<div class="widget-box">
    <div class="widget-title clearfix">
        <span class="icon"><i class="icon-th"></i></span>
        <h5 class="title">Explorer</h5>
    </div>
    <div class="widget-content">
    	<div class="explorer">
    		<ul class="explorer-tree">
    			<li class="item-folder">
    				<a href="index.php?view=backend&layout=items&action=view&name=home" title="">Home</a>
    			</li>
    		</ul>
    	</div>
    </div>
    <div class="widget-options">
    </div>
</div>