<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<ul class="inline">
				<!-- Smarty -->
				<li>
					Smarty&nbsp;
					<a href="http://www.smarty.net/docs/en/" title="Smarty Documentation">
					<?php $this->smartyVersion(); ?>
					</a>
				</li>
				<li class="divider-vertical"></li>
				<!-- Doctrine -->
				<li>
					Doctrine&nbsp;
					<a href="http://docs.doctrine-project.org/en/latest/" title="Doctrine Documentation">
					<?php $this->doctrineVersion(); ?>
					</a>
				</li>
				<li class="divider-vertical"></li>
				<!-- PureMVC -->
				<li>
					<a href="http://puremvc.org/pages/docs/PHP/docs/" title="PureMVC Documentation">
					PureMVC
					</a>
				</li>
				<li class="divider-vertical"></li>
				<!-- Bootstrap -->
				<li>
					Bootstrap&nbsp;
					<a href="http://twitter.github.com/bootstrap/" title="Bootstrap Documentation">
					2.3.0
					</a>
				</li>
				<li class="divider-vertical"></li>
				<!-- jQuery -->
				<li>
					jQuery&nbsp;
					<a href="http://api.jquery.com/" title="jQuery Documentation">
					<script type="text/javascript">document.write( jQuery.fn.jquery );</script>
					</a>
				</li>
				<li class="divider-vertical"></li>
				<!-- MySQL Workbenck Exporter -->
				<li>
					<a href="https://github.com/johmue/mysql-workbench-schema-exporter" title="MySQL Workbenck Exporter">
					MySQL Workbenck Exporter
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>