<?php $form = $this->getHelper()->getForm(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <?php $this->getChildHtml( "head" ); ?>
</head>
<body class="page-1column <?php echo $this->getBodyClass(); ?>">
    <?php $this->getChildHtml( "beforebody" ); ?>
	<div class="container">
		<div class="row">
        	<div class="notifications span12"><?php $this->getChildHtml( "notifications" ); ?></div>
		</div>
        <form
    		class="form-horizontal"
            id="<?php echo $form->getId(); ?>"
    		method="<?php echo $form->getMethod(); ?>"
    		enctype="<?php echo $form->getEnctype(); ?>"
			action="<?php echo htmlentities( $form->getAction() ); ?>" 
		>
	    <div class="row">
	    	<div class="content span6 offset3">
	    		<?php $this->getChildHtml( "content" ); ?>
	    		<?php $this->getChildHtml( "submit" ); ?>
			</div>
		</div>
		</form>
	</div>
	<?php $this->getChildHtml( "afterbody" ); ?>
    <?php $this->getChildHtml( "debugger" ); ?>
</body>
</html>