<p>Vous allez proc&eacute;der &agrave; l'installation du gestionnaire de contenu de votre site internet, pour se faire <b id="popover-cookie" data-trigger="hover" data-placement="top" data-content="Les cookies peuvent être utilisés pour mémoriser l'information sur l'utilisateur d'un site [...]. Par exemple un serveur web peut envoyer un cookie contenant le nom de l'utilisateur dernièrement utilisé pour se connecter à un site web à fin qu'il puisse être rempli dans les prochaines visites" title="Les Cookies">vos cookies doivent &ecirc;tre actives.</b></p>
<p>La configuration de votre serveur sera test&eacute;e lors de la prochaine &eacute;tape.<br>Cliquez sur le bouton continuer.</p>
<p>
	<i class="icon-share"></i>&nbsp;<a href="http://support.mozilla.com/fr/kb/Activer%20et%20désactiver%20les%20cookies?s=cookie&as=s">Active les cookies sous Firefox</a>
</p>
<script type="text/javascript">
//<![CDATA[
	jQuery( document ).ready( function()
	{
		var options = []; 
		jQuery( "#popover-cookie" ).popover( options );
	});
//]]>
</script>