<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<?php $this->getChildHtml( "head" ); ?>
<body class="page-1column <?php echo $this->getBodyClass(); ?>">
    <?php $this->getChildHtml( "beforebody" ); ?>
    <div class="jumbotron">
    	<div class="container"><?php $this->getChildHtml( "header" ); ?></div>
    </div>
	<div class="container">
		<?php $this->getChildHtml( "error" ); ?>
	</div>
	<?php $this->getChildHtml( "afterbody" ); ?>
    <?php $this->getChildHtml( "debugger" ); ?>
</body>
</html>